import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideLayout from "@/components/modules/sidebar/side-layout";
import Providers from "@/components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mini 16",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <SideLayout />
          <main className="pl-[200px] min-h-full">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
